# Generated by Django 2.0.6 on 2019-10-31 00:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_compras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Festa')),
                ('horainicio', models.TimeField(verbose_name='Hora Inicio')),
                ('horatermino', models.TimeField(verbose_name='Hora Termino')),
                ('valor', models.FloatField(verbose_name='Valor Total')),
            ],
            options={
                'verbose_name': 'Aluguel Agendado',
                'verbose_name_plural': 'Alugueis Agendados',
                'ordering': ('-data', 'horainicio'),
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('fone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'verbose_name_plural': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=20, verbose_name='Logradouro')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('complemento', models.CharField(max_length=30, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=15, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=15, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Cep number must be entered in the format: '64000000'. Up to 10 digits allowed.", regex='^\\+?1?\\d{8,10}$')])),
            ],
            options={
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='ItemTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição do Item')),
            ],
            options={
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('valor', models.FloatField(verbose_name='Valor Aluguel')),
                ('cor_toalha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ItemTema')),
            ],
            options={
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.DeleteModel(
            name='Livraria',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Endereco'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='temaescolhido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tema'),
        ),
    ]
